BEGIN;
ALTER TABLE public.user ADD COLUMN "password_hash" VARCHAR(255) DEFAULT '' NOT NULL;
ALTER TABLE public.user ADD COLUMN "password_update_time" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL;
COMMIT;
