BEGIN;
CREATE TYPE valid_onboarding_status AS ENUM (
  'ONBOARDING_STATUS_UNSPECIFIED',
  'ONBOARDING_STATUS_IN_PROGRESS',
  'ONBOARDING_STATUS_COMPLETED'
);
ALTER TABLE public.owner ADD COLUMN "onboarding_status" valid_onboarding_status DEFAULT 'ONBOARDING_STATUS_UNSPECIFIED';
COMMIT;
