server:
  port: 8080
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
  corsorigins:
    - http://localhost:3000
  edition: local-ce:dev
  disableusage: true
  debug: false
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  name: mgmt
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
usagebackend:
  host: usage.instill.tech
  port: 443
