server:
  port: 8084
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
  corsorigins:
    - http://localhost:3000
  edition: local-ce:dev
  disableusage: false
  debug: true
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: mgmt
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
usagebackend:
  tlsenabled: true
  host: usage.instill.tech
  port: 443
