server:
  privateport: 3084
  publicport: 8084
  https:
    cert:
    key:
  edition: docker-ce:dev
  usage:
    enabled: true
    tlsenabled: true
    host: usage.instill-ai.com
    port: 443
  debug: true
  defaultuseruid:
  instillcorehost: http://localhost:8080
pipelinebackend:
  host: pipeline-backend
  publicport: 8081
  https:
    cert:
    key:
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: mgmt
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
cache:
  redis:
    redisoptions:
      addr: redis:6379
influxdb:
  url: http://influxdb:8086
  token: i-love-instill-ai
  org: instill-ai
  bucket: instill-ai
  flushinterval: 10s
  https:
    cert:
    key:
otelcollector:
  enable: false
  host: otel-collector
  port: 4317
openfga:
  host: openfga
  port: 8080
temporal:
  hostport: temporal:7233
  namespace: mgmt-backend
  retention: 1d
  metricsport: 8096
  servername:
  serverrootca:
  clientcert:
  clientkey:
  insecureskipverify:
