server:
  adminport: 3084
  publicport: 8084
  https:
    cert:
    key:
  corsorigins:
  edition: local-ce:dev
  plugin: plugin
  disableusage: false
  debug: true
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: mgmt
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
usageserver:
  tlsenabled: true
  host: usage.instill.tech
  port: 443
