server:
  privateport: 3084
  publicport: 8084
  https:
    cert:
    key:
  edition: local-ce:dev
  usage:
    enabled: true
    tlsenabled: true
    host: usage.instill.tech
    port: 443
  debug: true
  defaultuseruid:
connectorbackend:
  host: connector-backend
  publicport: 8082
  https:
    cert:
    key:
pipelinebackend:
  host: pipeline-backend
  publicport: 8081
  https:
    cert:
    key:
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: mgmt
  version: 2
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
influxdb:
  url: http://influxdb:8086
  token: i-love-instill-ai
  org: instill-ai
  bucket: instill-ai
  flushinterval: 10 # In seconds for non-blocking batch mode
  https:
    cert:
    key:
log:
  external: false
  otelcollector:
    host: otel-collector
    port: 8095
