server:
  privateport: 3084
  publicport: 8084
  https:
    cert:
    key:
  edition: local-ce:dev
  usage:
    enabled: true
    tlsenabled: true
    host: usage.instill.tech
    port: 443
  debug: true
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: mgmt
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
log:
  external: true
  otelcollector:
    host: otel-collector
    port: 8095
