name: Sync Instill Core Version

on:
  push:
    branches:
      - main
      - huitang/ins-8272 # TODO: remove this branch

jobs:
  update-version:
    uses: instill-ai/instill-core/.github/workflows/update-service-version.yml@huitang/ins-8272
    with:
      service: mgmt
