name: Sync Instill Core Version

on:
  push:
    branches:
      - huitang/ins-8272-4
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Images"]
    types:
      - completed
    branches:
      - main

jobs:
  update-version:
    uses: instill-ai/instill-core/.github/workflows/update-service-version.yml@huitang/ins-8272-4
    with:
      service: mgmt
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
